# Use the official Microsoft .NET SDK image to build the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Copy everything
COPY . .
WORKDIR "/src/CatsStealer.WebApi"
# Debug
RUN ls -la

RUN dotnet restore "CatsStealer.WebApi.csproj"

RUN dotnet build "CatsStealer.WebApi.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "CatsStealer.WebApi.csproj" -c Release -o /app/publish

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CatsStealer.WebApi.dll"]